# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [5]:
# Create a 1-dimensional NumPy array using np.array()

array_1d = np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()

array_2d = np.array([[1, 2, 3],[4, 5, 6]])

# Create a 3-dimensional Numpy array using np.array()

array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])


Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [23]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)

print("1D array: \n",
      "Shape = ", array_1d.shape ,"\n",
      "Number of dimensions = " , array_1d.ndim,"\n",
      "Data type is " , array_1d.dtype , "\n",
      "Size = " ,array_1d.size , "\n",
      "Type is " ,type(array_1d)
      )


1D array: 
 Shape =  (3,) 
 Number of dimensions =  1 
 Data type is  int64 
 Size =  3 
 Type is  <class 'numpy.ndarray'>


In [24]:
# Attributes of 2-dimensional array
print("2D array: \n",
      "Shape = ", array_2d.shape ,"\n",
      "Number of dimensions = " , array_2d.ndim,"\n",
      "Data type is " , array_2d.dtype , "\n",
      "Size = " ,array_2d.size , "\n",
      "Type is " ,type(array_2d)
      )


2D array: 
 Shape =  (2, 3) 
 Number of dimensions =  2 
 Data type is  int64 
 Size =  6 
 Type is  <class 'numpy.ndarray'>


In [25]:
# Attributes of 3-dimensional array
print("3D array: \n",
      "Shape = ", array_3d.shape ,"\n",
      "Number of dimensions = " , array_3d.ndim,"\n",
      "Data type is " , array_3d.dtype , "\n",
      "Size = " ,array_3d.size , "\n",
      "Type is " ,type(array_3d)
      )

3D array: 
 Shape =  (2, 2, 3) 
 Number of dimensions =  3 
 Data type is  int64 
 Size =  12 
 Type is  <class 'numpy.ndarray'>


In [28]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created

import pandas as pd

df  = pd.DataFrame(array_2d)

df

0  1  2
0  1  2  3
1  4  5  6

In [37]:
# Create an array of shape (10, 2) with only ones
ones_array = np.ones((10,2))
ones_array

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [38]:
# Create an array of shape (7, 2, 3) of only zeros
zeros_array = np.zeros((7,2,3))
zeros_array


array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [40]:
# Create an array within a range of 0 and 100 with step 3
range_array = np.arange(0,100,3)
range_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [45]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array_int = np.random.randint(0,10, size=(7,2))
random_array_int

array([[8, 8],
       [8, 0],
       [4, 4],
       [4, 2],
       [7, 8],
       [1, 8],
       [7, 5]])

In [43]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_array_float = np.random.random((3,5))
random_array_float

array([[0.50764065, 0.88213929, 0.58945209, 0.24626641, 0.70851251],
       [0.21030203, 0.2627663 , 0.3388527 , 0.84689605, 0.1247633 ],
       [0.36597403, 0.72456889, 0.82783533, 0.66097419, 0.95903875]])

In [49]:
# Set the random seed to 42

np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)

random_array_int2 = np.random.randint(0,10, size=(4,6))

random_array_int2

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

The numbers stay the same, because the random seed is initalized as a constant number.

In [54]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable

arr = np.random.randint(1,10,size=(3,7))

print(arr)

# Find the unique numbers in the array you just created

print("unique numbers = ", np.unique(arr))

[[9 7 9 8 2 1 7]
 [7 8 5 3 8 6 3]
 [1 3 5 3 1 5 7]]
unique numbers =  [1 2 3 5 6 7 8 9]


In [55]:
# Find the 0'th index of the latest array you created

arr[0]

array([9, 7, 9, 8, 2, 1, 7])

In [61]:
# Get the first 2 rows of latest array you created

arr[:2]


array([[9, 7, 9, 8, 2, 1, 7],
       [7, 8, 5, 3, 8, 6, 3]])

In [89]:
# Get the first 2 values of the first 2 rows of the latest array

arr[ :2 ,:2]

array([[9, 7],
       [7, 8]])

In [91]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables

ones =  np.ones((3,5))

rand = np.random.randint(0,10,size=(3,5))

print(ones)
print(rand)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[3 8 2 6 5]
 [7 8 4 0 2]
 [9 7 5 7 8]]


In [92]:
# Add the two arrays together

added = ones + rand
added

array([[ 4.,  9.,  3.,  7.,  6.],
       [ 8.,  9.,  5.,  1.,  3.],
       [10.,  8.,  6.,  8.,  9.]])

In [93]:
# Create another array of ones of shape (5, 3)

ones2 = np.ones((5,3))

In [94]:
# Try add the array of ones and the other most recent array together

new_added = rand + ones2

new_added

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

The error is because the 2 arrays to be added are of different sizes.

To fix it, the array can be reshaped to the same size.

In [95]:
# Create another array of ones of shape (3, 5)

ones3 = np.ones((3,5))

In [96]:
# Subtract the new array of ones from the other most recent array

subtracted = rand - ones3

subtracted

array([[ 2.,  7.,  1.,  5.,  4.],
       [ 6.,  7.,  3., -1.,  1.],
       [ 8.,  6.,  4.,  6.,  7.]])

In [97]:
# Multiply the ones array with the latest array

multiplied = ones3 * rand

multiplied

array([[3., 8., 2., 6., 5.],
       [7., 8., 4., 0., 2.],
       [9., 7., 5., 7., 8.]])

In [98]:
# Take the latest array to the power of 2 using '**'

power = rand**2

power

array([[ 9, 64,  4, 36, 25],
       [49, 64, 16,  0,  4],
       [81, 49, 25, 49, 64]])

In [99]:
# Do the same thing with np.square()

np.square(rand)

array([[ 9, 64,  4, 36, 25],
       [49, 64, 16,  0,  4],
       [81, 49, 25, 49, 64]])

In [100]:
# Find the mean of the latest array using np.mean()

np.mean(rand)

5.4

In [101]:
# Find the maximum of the latest array using np.max()

np.max(rand)

9

In [102]:
# Find the minimum of the latest array using np.min()

np.min(rand)

0

In [103]:
# Find the standard deviation of the latest array

np.std(rand)

2.6025628394590847

In [104]:
# Find the variance of the latest array

np.var(rand)

6.7733333333333325

In [108]:
# Reshape the latest array to (3, 5, 1)
reshaped = rand.reshape(3,5,1)

reshaped

array([[[3],
        [8],
        [2],
        [6],
        [5]],

       [[7],
        [8],
        [4],
        [0],
        [2]],

       [[9],
        [7],
        [5],
        [7],
        [8]]])

In [110]:
# Transpose the latest array

transpose = reshaped.T

transpose

array([[[3, 7, 9],
        [8, 8, 7],
        [2, 4, 5],
        [6, 0, 7],
        [5, 2, 8]]])

What does the transpose do?

switch the rows and columns

In [111]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)

arr1 = np.random.randint(0,10,size=(3,3))
arr2 = np.random.randint(0,10,size=(3,2))

print(arr1)
print(arr2)

[[3 0 0]
 [9 3 6]
 [1 2 0]]
[[4 0]
 [7 0]
 [0 1]]


In [114]:
# Perform a dot product on the two newest arrays you created

dot1 = arr1.dot(arr2)

dot1

array([[12,  0],
       [57,  6],
       [18,  0]])

In [122]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)

arr3 = np.random.randint(0,10,size=(4,3))
arr4 = np.random.randint(0,10,size=(4,3))

In [123]:
# Perform a dot product on the two newest arrays you created

dot2 = arr3.dot(arr4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [124]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both

arr4 = arr4.T
dot2 = arr3.dot(arr4)

dot2

array([[ 72,  84,  36, 103],
       [ 80, 100,  40, 115],
       [ 86, 142,  43, 124],
       [  4,   8,   2,   5]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [136]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables


arr5 = np.random.randint(0,10,size=(4,3))
arr6 = np.random.randint(0,10,size=(4,3))

print(arr5)
print(arr6)

[[0 4 2]
 [0 3 4]
 [6 0 2]
 [1 8 9]]
[[5 9 2]
 [7 7 1]
 [5 6 1]
 [9 1 9]]


In [137]:
# Compare the two arrays with '>'

arr5 > arr6

array([[False, False, False],
       [False, False,  True],
       [ True, False,  True],
       [False,  True, False]])

What happens when you compare the arrays with `>`?

compare between each element in one array with the corresponding element in the other array

In [138]:
# Compare the two arrays with '>='

arr5 >= arr6

array([[False, False,  True],
       [False, False,  True],
       [ True, False,  True],
       [False,  True,  True]])

In [139]:
# Find which elements of the first array are greater than 7

arr5 > 7

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False,  True,  True]])

In [140]:
# Which parts of each array are equal? (try using '==')

arr5 == arr6


array([[False, False,  True],
       [False, False, False],
       [False, False, False],
       [False, False,  True]])

In [141]:
# Sort one of the arrays you just created in ascending order
np.sort(arr5)

array([[0, 2, 4],
       [0, 3, 4],
       [0, 2, 6],
       [1, 8, 9]])

In [142]:
# Sort the indexes of one of the arrays you just created

np.argsort(arr6)

array([[2, 0, 1],
       [2, 0, 1],
       [2, 0, 1],
       [1, 0, 2]])

In [144]:
# Find the index with the maximum value in one of the arrays you've created

np.argmax(arr6)

1

In [145]:
# Find the index with the minimum value in one of the arrays you've created

np.argmin(arr6)

5

In [155]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created

np.argmax(arr6,axis=1)

array([1, 0, 1, 0])

In [156]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created

np.argmin(arr6 , axis=0)

array([0, 3, 1])

In [161]:
# Create an array of normally distributed random numbers

np.random.normal(size=(10))

array([ 0.35730454, -0.41453181,  0.08019871, -0.89312027, -0.33481725,
        1.56038014,  0.128551  ,  0.54957635, -1.27087181,  2.38903596])

In [163]:
# Create an array with 10 evenly spaced numbers between 1 and 100

np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.